name: macro_sample
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  macros:
  json: ^0.20.2
dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
